import Head from "next/head";
import NavBarCookies from "@/components/NavBarCookies";
import Cookies from "@/components/Cookies";
import CookiesRecipies from "@/components/CookiesRecipies";
import NavBar20Min from "@/components/NavBar20Min";
import Min from "@/components/Min";
import MinRecipies from "@/components/20MinRecipies";

export default function Home() {
  return (
    <div>
      <Head>
        <title>The Cookbook </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <NavBar20Min />
      </header>

      <main>
        <Min />
        <MinRecipies />
      </main>
    </div>
  );
}
