import Head from "next/head";
import NavBarCookies from "@/components/NavBarCookies";
import Cookies from "@/components/Cookies";
import CookiesRecipies from "@/components/CookiesRecipies";

export default function Home() {
  return (
    <div>
      <Head>
        <title>The Cookbook </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <NavBarCookies />
      </header>

      <main>
        <Cookies />
        <CookiesRecipies />
      </main>
    </div>
  );
}
