import Head from "next/head";
import NavBarFish from "@/components/NavBarFish";
import Fish from "@/components/Fish";
import FishRecipies from "@/components/FishRecipies";
import NavBarGFSweet from "@/components/NavBarGFSweet";
import GlutenFreeSweet from "@/components/GlutenFreeSweet";
import GlutenFreeSweetRecipies from "@/components/GlutenFreeSweetRecipies";

export default function Home() {
  return (
    <div>
      <Head>
        <title>The Cookbook </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <NavBarGFSweet />
      </header>

      <main>
        <GlutenFreeSweet />
        <GlutenFreeSweetRecipies />
      </main>
    </div>
  );
}
