import Head from "next/head";
import image from "next/image";
import NavBar from "../components/NavBar";
import Homepage from "../components/Homepage";
import Recipe from "../components/Recipe";

export default function Home() {
  return (
    <div>
      <Head>
        <title>The Cookbook </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <NavBar />
      </header>

      <main>
        <Homepage />
        <Recipe />
      </main>
    </div>
  );
}
