import Head from "next/head";
import image from "next/image";
import NavBar from "../components/NavBar";
import Meat from "../components/Meat";
import Recipe from "../components/Recipe";
import NavBarMeat from "@/components/NavBarMeat";
import MeatRecipies from "@/components/MeatRecipies";

export default function Home() {
  return (
    <div>
      <Head>
        <title>The Cookbook </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <NavBarMeat />
      </header>

      <main>
        <Meat />
        <MeatRecipies />
      </main>
    </div>
  );
}
